### ISSUE TITLE
Seemingly valid GraphQL API query returns null when data is expected

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-flutter#1445]
### Description

A GraphQL API query, specifically this code
```dart
    final request =
        GraphQLRequest<String>(document: doc, variables: {'id': id});
    final response = await Amplify.API.query(request: request).response;
```
where `id` is the ID you get from the user model instance in the DB and `doc` contains the query below, returns `response.data == null`, i.e. it returns a `null` user instance result, even though `id` is verified to be correct by looking at the DB. 

The query in `doc` is:
```graphql
query GetUserProfile($id: ID!) {
            getUser(id: $id) {
              id
              colorIndex
              imageType
              displayName
              initials
              bio 
              place
              nPlays
              nProjects
              nArrangements
              nPlaylists
              bytesQuota
              bytesUsed
              email
              nUpdatesInLast24h
              nUploadsInLast24h
              totalEarned
              uploadedAt
              createdAt
              updatedAt
            }
          }
```

Here is the user model that caused the null result, as provided via the AWS DynamoDB console in the browser, in JSON:
```json
{
 "id": "f4fd0359-1b78-4951-a945-a62f2c0c5a62",
 "nProjects": 0,
 "nUpdatesInLast24h": 0,
 "imageType": "icon",
 "bio": "",
 "nPlays": 0,
 "createdAt": "2022-03-08T20:52:16.357Z",
 "nUploadsInLast24h": 0,
 "email": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "bytesQuota": 2000000000,
 "totalEarned": 0,
 "displayName": "",
 "bytesUsed": 0,
 "updatedAt": "2022-03-08T20:52:16.357Z",
 "place": "",
 "owner": "f4fd0359-1b78-4951-a945-a62f2c0c5a62",
 "colorIndex": 8,
 "nPlaylists": 0,
 "uploadedAt": "2022-03-08T20:52:16.357Z",
 "nArrangements": 0,
 "initials": ""
}
```
The schema for the `User` model is
```graphql
type User
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      # the 'allow: owner' rule is needed in order to have an owner
      # field created for us, it is needed here, at the model level
      { allow: owner, operations: [read] }
      { allow: private, operations: [read] }
      { allow: public, provider: iam, operations: [read] }
    ]
  ) {
  id: ID! @primaryKey
  colorIndex: Int!
  imageType: ImageType!
  displayName: String!
  initials: String!
  bio: String!
  place: String!
  nPlays: Int!
  nProjects: Int!
  nArrangements: Int!
  nPlaylists: Int!
  bytesQuota: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  bytesUsed: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  email: String! @auth(rules: [{ allow: owner, operations: [read] }])
  nUpdatesInLast24h: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  nUploadsInLast24h: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  totalEarned: Float! @auth(rules: [{ allow: owner, operations: [read] }])
  uploadedAt: AWSDateTime! @auth(rules: [{ allow: owner, operations: [read] }])
  projects: [Project] @hasMany
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
``` 

The Android 8.0 Samsung S7 simulator reports exceptions in the Java code even though no exceptions are thrown in the Dart code, which just returns null instead. Here's the simulator log of the Java exceptions from the VSCode debug console, right after you call the query:
```
D[/AWSMobileClient]()(13181): hasFederatedToken: true provider: cognito-idp.us-east-1.amazonaws.com[/us-east-1_zLuq9luH8]()
D[/AWSMobileClient]()(13181): waitForSignIn: userState:SIGNED_IN
D[/AWSMobileClient]()(13181): getCredentials: Validated user is signed-in
E[/amplify]():flutter:api(13181): GraphQL mutate operation failed
E[/amplify]():flutter:api(13181): NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
E[/amplify]():flutter:api(13181): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:145)
E[/amplify]():flutter:api(13181): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E[/amplify]():flutter:api(13181): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E[/amplify]():flutter:api(13181): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E[/amplify]():flutter:api(13181): 	at java.lang.Thread.run(Thread.java:764)
W[/AtomicResult]()(query)(13181): Attempted to send success value after initial reply
E[/flutter]() (13181): [ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: ApiException(message: OkHttp client request failed., recoverySuggestion: Irrecoverable error, underlyingException: null)
``` 
Notice how it says "GraphQL mutate operation failed" but this is not a GraphQL mutate operation, it's a GraphQL query operation.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. See bug report above to set up a GraphQL schema with the user model above.
2. See bug report above and run the query call that causes the bug. You'll need:
    * an `id` - which you get from an existing user that you need to have already 
       created in DynamoDB with an instance of the User model.
    * the query `doc` - use the one in the description section above
    * please make sure that (a) a user is signed in, (b) the user signed in when making the query call is querying **themselves**, i.e, their ID is the value of `id` in the query call
      
Running this query reproduces the bug if you get `null` as a result.

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on Debian GNU/Linux 11 (bullseye) 5.10.0-11-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.3
todo_private 1.0.0+1

dependencies:
- amplify_api 0.4.1 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.1 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_authenticator 0.1.0 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
- amplify_datastore 0.4.1 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- hooks_riverpod 1.0.3 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.1 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.4.1 [flutter meta amplify_core]
- amplify_core 0.4.1 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.1 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.1 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- flutter_hooks 0.18.2+1 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_riverpod 1.0.3 [collection flutter meta riverpod state_notifier]
- intl 0.17.0 [clock path]
- json_annotation 4.4.0 [meta]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- riverpod 1.0.3 [collection meta state_notifier]
- sky_engine 0.0.99
- state_notifier 0.7.2+1 [meta]
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
```

### Device

Android simulator qemu on Debian 11 

### OS

Android 8.0

### CLI Version

7.6.23

**Comment by ragingsquirrel3** [comment]
@dorontal this looks similar to an issue that was closed a while back https://github.com/aws-amplify/amplify-flutter/issues/1175 . While I think that should be fixed with the version you are using, I wonder if there might be other special characters in the request that are causing issues with Android? Or maybe that fix isn't working as expected?

One thing that helped to debug the other issue was to reduce the query request to something as small and simple as possible that works (like maybe just getting the id) and then iteratively adding things until it's clear which part of the request is causing it to be invalid.

**Comment by dorontal** [comment]
Hi @ragingsquirrel3 - thanks for responding to this bug. I don't believe there are any special characters in `doc` in the code above, i.e. in the GraphQL document that gets submitted in the query. 

Regarding the simpler test case reproductions, sure, but that's easy to do: one just has to use the model I provided as a starting point then take out parts of it one by one, until the bug no longer shows up. I will not have time to do this in the near future, unfortunately, but in a few weeks, if this bug is still around, I may be able to do that. 

In the meantime, just to ensure my first point above is correct and that I'm not making any wrong assumptions. The GraphQL query document (`doc`) gets constructed by concatenating 3 Dart string constants as follows:
```dart
   doc = docStart + signedInFields + docEnd
```
where `docStart, signedInFields`, and `docEnd` are:
```dart
const docStart = '''
    query GetUserProfile(\$id: ID!) {
      getUser(id: \$id) {
        id
        colorIndex
        imageType
        displayName
        initials
        bio 
        place
        nPlays
        nProjects
        nArrangements
        nPlaylists
  ''';
const signedInFields = '''
        bytesQuota
        bytesUsed
        email
        nUpdatesInLast24h
        nUploadsInLast24h
        totalEarned
        uploadedAt
  ''';
const docEnd = '''
        createdAt
        updatedAt
      }
    }
  ''';
```
I don't believe this query causes any special characters that would be a problem for GraphQL - unless the carriage returns are not allowed, but I have not seen such restriction.

**Comment by dorontal** [comment]
Yup, just checked and removed all carriage return and any possible other special characters in that query document, with spaces being the only non alphanumeric character in the document, but the same issue remains.

**Comment by ragingsquirrel3** [comment]
@dorontal one more question: Does your `GraphqlResponse` have any errors in `response.errors`?

**Comment by dorontal** [comment]
@ragingsquirrel3  yes - just checked and there were errors in `response.errors` - in from the VSCode debug console, screenshot:
![response_errors](https://user-images.githubusercontent.com/5935957/157560926-0e7ac363-c5d6-419b-833b-c18abc59548c.png)

It looks like an unauthorized exception.  I have a version of the same app but in Angular / Javascript - I believe it did not get an unauthorized exception. It would take some time for me to rebuild this dormant version and see if it also gets those exceptions (The Javascript version used to have unauthorized exceptions a while ago for me but that was solved: as soon as I added the field `owner` manually to the DB table and had set it to be the same as `id` of the user, no longer did such exceptions show up in the Javascript version and it actually worked - the query succeeds in it. I will check soon, however, to make sure that this is still the case because the Javascript version of this app is a few versions of Amplify behind).

This previous CLI issue was the one dealing with unauthorized exceptions in the Javascript version : https://github.com/aws-amplify/amplify-cli/issues/9855 -- it may or may not be relevant -- I'll check to make sure that the Javascript version that runs the same exact query actually succeeds with it as I claim.

**Comment by ragingsquirrel3** [comment]
@dorontal thanks for the information. It looks like your schema requires multiple authorization modes and cognito user pool mode to be used for this request as it is reading owner-only fields. Have you enabled multiple authorization modes from the CLI for this app? What is the current auth mode for your backend? The behavior you are seeing looks consistent with attempting the request with IAM auth mode (though I'm curious if the query would work if you omitted all the fields marked as owner read in the schema).

There is some info for multi auth modes on https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#configure-multiple-authorization-modes but it looks like you are not passing the `apiName` parameter to your `GraphQLRequest` which you will have to do after following the CLI/config instructions to specify using user pools auth mode for this request.

The setup in flutter/android/ios is different than JS way of doing this as I believe JS lets you simply pass the `authorizationMode` to the request which is not available in amplify-flutter. Also, I don't think this related to special characters like I initially suspected (my bad).

**Comment by dorontal** [comment]
@ragingsquirrel3 thank you for this documentation link! I've been searching for multi-auth related documentation and how to switch auth modes. I just checked and indeed the `amplifyconfiguration.dart` is set up for `IAM` - this explains the "unauthorized" errors, because the query asks for some fields that only the owner (== Cognito mode) is allowed to see. I will try to change to using Cognito mode according to this link and will report.

**Comment by dorontal** [comment]
@ragingsquirrel3  yup - as soon as I switched over to using the correct authorization model (Cognito user pools) via the link that you sent, everything works and there are no longer any authorization errors. 

Thank you very much for sending the link on how to switch modes - this revelation is a total breakthrough for us here!

As far as I'm concerned this issue is completely solved and not an issue anymore.

**Comment by ragingsquirrel3** [comment]
@dorontal glad you got this resolved! Will close this issue.
