### ISSUE TITLE
NotAuthorizedException after submitting OTP

### ISSUE THREAD

**Issue by bhargavAtgithub** [aws-amplify/amplify-flutter#1491]
### Description

Using Amplify-Flutter to create OTP authentication flow. 

Generate amplifyConfiguration.dart file
Wrote 4 lambdas
- Pre sign up
- Create Challenge
- Define Challenge
- Verify Auth challenge

Successfully I was able to send OTP using Amplify.Auth.signUp with a phone number and dummy password, triggers pre-signUp lambda which auto confirms user, email and phone number. 
Then by using Amplify.Auth.signIn with phone number and same dummy password to trigger Define Auth Challenge and then create auth challenge to generate OTP and send to the user.
With otp, another lambda verfiyAuth is trigger with Amplify.Auth.confirmSignIn

Everything worked as expected except for confirmSignIn. 
Which is giving error -> 
flutter: NotAuthorizedException(message: Incorrect username or password., recoverySuggestion: Check whether the given values are correct and the user is authorized to perform the operation., underlyingException: null) 

Pre Sign Up lambda
```
exports.handler = (event, context, callback) => {
  // Confirm the user
  event.response.autoConfirmUser = true;
  // Set the email as verified if it is in the request
  if (event.request.userAttributes.hasOwnProperty('email')) {
    event.response.autoVerifyEmail = true;
  }
  // Set the phone number as verified if it is in the request
  if (event.request.userAttributes.hasOwnProperty('phone_number')) {
    event.response.autoVerifyPhone = true;
  }
  // Return to Amazon Cognito
  callback(null, event);
};
```

Define auth lambda
```
exports.handler = (event, context) => {
  console.log('Define event start')
  console.log(event);
  console.log(event.request.session); 
  if (event.request.session.length === 0) {
    event.response.issueTokens = false;
    event.response.failAuthentication = false;
    event.response.challengeName = 'CUSTOM_CHALLENGE';
  }else if (event.request.session.length === 1 && 
    event.request.session[0].challengeName === 'SRP_A') {
    event.response.issueTokens = false;
    event.response.failAuthentication = false;
    event.response.challengeName = 'CUSTOM_CHALLENGE';
  } 
  else if (
    event.request.session.length === 1 &&
    event.request.session[0].challengeName === 'CUSTOM_CHALLENGE' &&
    event.request.session[0].challengeResult === true
  ) {
    event.response.issueTokens = true;
    event.response.failAuthentication = false;
  } else {
    event.response.issueTokens = false;
    event.response.failAuthentication = true;
  }
  console.log(event.response);
  context.done(null, event);
};
```

Even.request.session is always SRP_A

And then create auth 
```
const AWS = require('aws-sdk');
exports.handler = (event, context, callback) => {
  //Create a random number for otp
  const challengeAnswer = Math.random().toString(10).substring(2, 6);
  console.log("event request start")
  console.log(event.request)
  console.log("event request end")
  const phoneNumber = event.request.userAttributes.phone_number;
  //sns sms
  const sns = new AWS.SNS({ region: 'ap-south-1' });
  sns.publish(
    {
      Message: 'Your Login OTP is: ' + challengeAnswer,
      PhoneNumber: phoneNumber,
      MessageStructure: 'string',
      MessageAttributes: {
        'AWS.SNS.SMS.SenderID': {
          DataType: 'String',
          StringValue: 'AMPLIFY',
        },
        'AWS.SNS.SMS.SMSType': {
          DataType: 'String',
          StringValue: 'Transactional',
        },
      },
    },
    function (err, data) {
      if (err) {
        console.log(err.stack);
        console.log(data);
        return;
      }
      return data;
    }
  );
  //set return params
  event.response.privateChallengeParameters = {};
  event.response.privateChallengeParameters.answer = challengeAnswer;
  event.response.challengeMetadata = 'CUSTOM_CHALLENGE';
  callback(null, event);
};
```

And finally verify auth 
```
exports.handler = (event, context) => {
  console.log(event, event.request, event.response);
  if (event.request.privateChallengeParameters.answer === event.request.challengeAnswer) {
    event.response.answerCorrect = true;
    console.log("true");
  } else {
    event.response.answerCorrect = false;
  }
  console.log(event);
  context.done(null, event);
};
```

Flutter Functions

```
void sendOTP(phoneNumber) async {
    try {
      Map<CognitoUserAttributeKey, String> userAttributes = {
        CognitoUserAttributeKey.phoneNumber: phoneNumber,
      };

      SignUpResult res = await Amplify.Auth.signUp(
        username: phoneNumber,
        password: "Password123#",
        options: CognitoSignUpOptions(
          userAttributes: userAttributes,
        ),
      );
    } catch (err) {
      print(err);
    }

    try {
      await Amplify.Auth.signOut();
    } on AuthException catch (err) {
      print(err);
    }

    try {
      Map<String, String> signInAttributes = {
        "phone_number": phoneNumber,
      };

      SignInResult sign_in_res = await Amplify.Auth.signIn(
        username: phoneNumber,
        password: 'Password123#',
        options: CognitoSignInOptions(clientMetadata: signInAttributes),
      );
      // ignore: avoid_print
      print(sign_in_res.isSignedIn);
      // ignore: avoid_print
      print(sign_in_res.nextStep);

      authenticatedUser = User(phoneNumber: phoneNumber);
      _authController.add(authenticatedUser);
    } catch (err) {
      print(err);
    }
    // ignore: avoid_print
    print("signning in");
  }
```
```
  void verifyOTP(phoneNumber, code) async {
    try {
      SignInResult res = await Amplify.Auth.confirmSignIn(
        confirmationValue: code,
      );
      // ignore: avoid_print
      print(res.isSignedIn);
      authenticatedUser = User(phoneNumber: phoneNumber, isAuthenticated: true);
      _authController.add(authenticatedUser);
    } catch (err) {
      print(err);
    }
    try {
      final user = await Amplify.Auth.getCurrentUser();
      print('user: $user');
    } catch (err) {
      print(err);
    }
  }
```

And verify OTP throws the error 
NotAuthorizedException(message: Incorrect username or password., recoverySuggestion: Check whether the given values are correct and the user is authorized to perform the operation., underlyingException: null)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

I've performed the same on both IOS and Android

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.3 21E230 darwin-arm, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.2
r_flutter 1.0.0+1

dependencies:
- amplify_analytics_pinpoint 0.4.2 [amplify_analytics_plugin_interface amplify_analytics_pinpoint_android amplify_analytics_pinpoint_ios amplify_core flutter plugin_platform_interface]
- amplify_auth_cognito 0.4.2 [flutter amplify_auth_plugin_interface amplify_core amplify_auth_cognito_android amplify_auth_cognito_ios collection plugin_platform_interface]
- amplify_core 0.4.2 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore 0.4.2 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.2 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- provider 6.0.2 [collection flutter nested]

transitive dependencies:
- amplify_analytics_pinpoint_android 0.4.2 [flutter]
- amplify_analytics_pinpoint_ios 0.4.2 [flutter]
- amplify_analytics_plugin_interface 0.4.2 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.2 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.4.2 [flutter]
- amplify_auth_cognito_ios 0.4.2 [amplify_core flutter]
- amplify_auth_plugin_interface 0.4.2 [flutter meta amplify_core]
- amplify_datastore_plugin_interface 0.4.2 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.2 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- json_annotation 4.4.0 [meta]
- material_color_utilities 0.1.3
- meta 1.7.0
- nested 1.0.0 [flutter]
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- petitparser 4.4.0 [meta]
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- xml 5.3.1 [collection meta petitparser]
```

### Device

N/A

### OS

N/A

### CLI Version

7.6.25

### Additional Context

In Federated Identities:
Authentication providers is Cognito
with correct pool id and app client id
Authenticated role selection -> use default role

**Comment by haverchuck** [comment]
Issue resolved via Discord.

**Comment by twink1e** [comment]
hello @haverchuck how was the issue resolved? I'm facing the same problem.
although I set `"authenticationFlowType": "CUSTOM_AUTH"` in my amplifyconfiguration.dart, in my Define auth lambda I still get SRP_A

**Comment by rhamnett** [comment]
@haverchuck what was the issue please?

**Comment by anilkr90251** [comment]
@haverchuck I am having the same issue can you provide solution?
