### ISSUE TITLE
FAILURE: Build failed with an exception. Flutter 2.0

### ISSUE THREAD

**Issue by Yonkokilasi** [aws-amplify/amplify-flutter#432]
**Describe the bug**
FAILURE: Build failed with an exception.

* Where:

Build file '*/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.1.0/android/build.gradle' line: 62

* What went wrong:
A problem occurred evaluating root project 'amplify_auth_cognito'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().

  Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**To Reproduce**
1. Run flutter build apk --release // flutter build apk
2. Make sure you are running Flutter 2.0
3. You will see the error  posted above in the output

**Expected behavior**
I am able to build an apk successfully

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
- Android
- iOS

**Comment by Amplifiyer** [comment]
@Yonkokilasi can you post your `flutter doctor -v` output here?

**Comment by Yonkokilasi** [comment]
> @Yonkokilasi can you post your `flutter doctor -v` output here?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (1 available)

**Comment by Amplifiyer** [comment]
@Yonkokilasi thanks for the details. My setup is exactly the same as yours and I am able to build apps (android release) that have amplify_auth_cognito as dependency with flutter 2.0. Will it be possible for you to host a minimal reproducible app on github where we can pull down and reproduce this issue?

**Comment by trinanda98** [comment]
Hi @Amplifiyer @Yonkokilasi has anyone found the solution yet? We're also facing this exact problem and it came out of nowhere. We were able to run it two days ago (Sunday), and hasn't done anything to the code ever since.

<img width="817" alt="Screenshot (8)" src="https://user-images.githubusercontent.com/43907852/111251437-d20d1100-8641-11eb-9de4-77efaa79f04e.png">
<img width="818" alt="Screenshot (9)" src="https://user-images.githubusercontent.com/43907852/111251447-d802f200-8641-11eb-80e6-96b85b5b4bba.png">


Flutter doctor result is fine

[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.1 at C:\flutter\flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\trina\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\trina\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\trina\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • POCO F2 Pro (mobile) • 36572c01 • android-arm64  • Android 11 (API 30)
    • Chrome (web)         • chrome   • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)           • edge     • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!

**Comment by Amplifiyer** [comment]
It looks like that jcenter was down yesterday during the time you ran into this issue https://status.bintray.com/
Can you try again and let us know if it's resolved on its own?

**Comment by bobosette** [comment]
I don't know if this can be useful....but i faced this problem 20 minutes ago (with flutter 1.22) and i fixed it by changing on the build.gradle the minSdkVersion (from 16 to 21)

**Comment by ken-ng-esotec** [comment]
im facing this issue too, any support on this please?

**Comment by Yonkokilasi** [comment]
> I don't know if this can be useful....but i faced this problem 20 minutes ago (with flutter 1.22) and i fixed it by changing on the build.gradle the minSdkVersion (from 16 to 21)

The minSDK is already 21
`group 'com.amazonaws.amplify.amplify_auth_cognito'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: './coverage.gradle'

def amplifyCore = findProject(':amplify_core')

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
        test.resources.srcDirs += '../test/resources'
    }
    defaultConfig {
        minSdkVersion 21
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    buildTypes {
        debug {
            testCoverageEnabled = true
        }
    }
}

dependencies {
    api amplifyCore
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.amplifyframework:aws-auth-cognito:1.16.13'
    testImplementation 'junit:junit:4.13'
    testImplementation 'org.mockito:mockito-core:3.1.0'
    testImplementation 'org.mockito:mockito-inline:3.1.0'
    testImplementation 'androidx.test:core:1.2.0'
    testImplementation 'org.robolectric:robolectric:4.3.1'
}
`

**Comment by Yonkokilasi** [comment]
> @Yonkokilasi thanks for the details. My setup is exactly the same as yours and I am able to build apps (android release) that have amplify_auth_cognito as dependency with flutter 2.0. Will it be possible for you to host a minimal reproducible app on github where we can pull down and reproduce this issue?

This will not be possible

**Comment by Yonkokilasi** [comment]
A new error is now showing @Amplifiyer 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/yonko/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.1.0/android/build.gradle' line: 62

* What went wrong:
A problem occurred evaluating root project 'amplify_auth_cognito'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().

  Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s


Exception: The plugin amplify_auth_cognito could not be built due to the issue above.
```

**Comment by SalahAdDin** [comment]
> A new error is now showing @Amplifiyer
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.1.0/android/build.gradle' line: 62
> 
> * What went wrong:
> A problem occurred evaluating root project 'amplify_auth_cognito'.
> > Cannot convert a null value to an object of type Dependency.
>   The following types/formats are supported:
>     - Instances of Dependency.
>     - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
>     - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
>     - FileCollections, for example files('some.jar', 'someOther.jar').
>     - Projects, for example project(':some:project:path').
>     - ClassPathNotation, for example gradleApi().
> 
>   Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> 
> 
> Exception: The plugin amplify_auth_cognito could not be built due to the issue above.
> ```

It is a conflict with the new **Flutter**'s version.

**Comment by WingCH** [comment]
same problem

**Comment by PriyaSindkar** [comment]
> A new error is now showing @Amplifiyer
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.1.0/android/build.gradle' line: 62
> 
> * What went wrong:
> A problem occurred evaluating root project 'amplify_auth_cognito'.
> > Cannot convert a null value to an object of type Dependency.
>   The following types/formats are supported:
>     - Instances of Dependency.
>     - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
>     - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
>     - FileCollections, for example files('some.jar', 'someOther.jar').
>     - Projects, for example project(':some:project:path').
>     - ClassPathNotation, for example gradleApi().
> 
>   Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> 
> 
> Exception: The plugin amplify_auth_cognito could not be built due to the issue above.
> ```

facing the same issue with Flutter SDK 2.0.3

**Comment by samuelchanx** [comment]
Same problem

**Comment by being-yash-t** [comment]
Any solution??

**Comment by CamronLDNF** [comment]
Same here

**Comment by raphire08** [comment]
same problem. Is there any solution?

**Comment by haverchuck** [comment]
Could somebody please post a pubspec file and an android/build.gradle file for an app that is reproducing this behavior?

**Comment by fdarsot** [comment]
having the same issue

**Comment by fdarsot** [comment]
So i was able to resolve (resolve isnt really the right word) but i was able to figure out that one of the other packages i was using in my pubspec.yaml file was interfering with this package. 

once i removed it, all was well again.

bad news is i need to find another package to use for that one i just took out.

**Comment by raphire08** [comment]
@fdarsot

Which package was that ?

**Comment by fdarsot** [comment]
@raphire08  https://pub.dev/packages/background_locator

**Comment by raphire08** [comment]
@haverchuck 

Please find pubsepc and android.build. Apologies for word document.

[pubspec.docx](https://github.com/aws-amplify/amplify-flutter/files/6558138/pubspec.docx)
[build_gradle.docx](https://github.com/aws-amplify/amplify-flutter/files/6558139/build_gradle.docx)

**Comment by raphire08** [comment]
@haverchuck 

I did some changes and it worked, but I don't know which one did the resolution

1. updated the Kotlin_version in build.gradle to 1.3.72
2. updated the classpath 'com.android.tools.build:gradle:4.1.3' 
3. updated grade version to 6.5
4. target SDK 30 (min SDKVerion was already 21)

Was able to build successfully then for amplify_flutter ^0.1.4 and amplify_auth_cognito ^0.1.4

**Comment by ollija** [comment]
Having this issue

**Comment by cshfang** [comment]
@ollija would it be possible to share a minimal project where you find this to be reproducible? Any additional information about the current state of your project (`pubspec.yaml`, `build.gradle`, etc) would be helpful. The original issue was opened against amplify flutter version 0.1.0 and the latest released version is 0.2.0 so I'm wondering (hoping?) that maybe the issue was fixed somewhere in between.

**Comment by ikartikgautam** [comment]
Even i am facing same issue

**Comment by epomeranz** [comment]
I'm having the same issue on the flutter's amplify example project: https://github.com/aws-amplify/amplify-flutter

Any suggestions?

**Comment by raaone7** [comment]
all I had similar issue, adding 
`amplify_core: ^0.2.2` in pubspec.yaml
solved the problem , worth trying it out

**Comment by offlineprogrammer** [comment]
Hi All

Is anyone still facing the issue with the latest release 

Regards
Mo
