### ISSUE TITLE
0.1.1 breaks hot restart for ios

### ISSUE THREAD

**Issue by ken-ng-esotec** [aws-amplify/amplify-flutter#498]
**Describe the bug**
Hot restart does not work after upgrade to v1.0.1. Tested in both Android Studio and VSCode.
**Issue only affect ios**. Android is working.

**To Reproduce**
1. Run in ios with amplify libraries v.0.1.0
2. Try hot restart - works
3. Upgrade to amplify libraries v0.1.1
4. Run in ios
5. Hot restart is broken "Lost connection to device." - Verbose log does not give any further info except "Service protocol connection closed" 

Flutter Doctor below:
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/keng/flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/keng/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/keng/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 203.7759

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • 44CE901B-1E28-4329-BDB9-97D00EB2F174
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 89.0.4389.114
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)

• No issues found!

**Comment by haverchuck** [comment]
@ken-ng-esotec Could you please post the code you are using to call `.configure` and `.addPlugin`, including any Flutter lifecyle hook you might be using?

**Comment by SalahAdDin** [comment]
It breaks also in android.

**Comment by Ashish-Nanda** [comment]
@ken-ng-esotec @SalahAdDin
We are aware of a hot restart issue that occurs when `addPlugin` and `configure` are called for a second time. Currently the native libraries we use underneath allow for these methods to be called only once, and the state is persisted even after a hot restart.

We have a fix in progress that we are testing, and are working on getting it released sometime next week.

**Comment by haverchuck** [comment]
@ken-ng-esotec The issue with hot restart should be fixed in version 0.1.2!

**Comment by SalahAdDin** [comment]
> @ken-ng-esotec The issue with hot restart should be fixed in version 0.1.2! You may need to delete your Podfile.lock in order to get the new version of amplify-ios, upon which this change is dependent.

They are very good news, thanks!!!

**Comment by Ashish-Nanda** [comment]
@ken-ng-esotec @SalahAdDin Could you let us know if hot restart works for you in version `0.1.2`?

**Comment by SalahAdDin** [comment]
@Ashish-Nanda Well, it seems to be working good on **Android**.

Does it mean we don't need to throw an error for this case anymore?
```dart
try {
    await Amplify.configure(amplifyconfig);
  } on AmplifyAlreadyConfiguredException {
    print(
        "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
  } catch (e) {
    print(e);
  }
```

**Comment by bulwinkel** [comment]
Hi team, any update here? I have just updated to 0.1.3 and am still experiencing this issue on iOS.

I am running on the simulator on an iPhone 12 mini, iOS 14.4

I completed the following steps:
- deleted the `podfile.lock` 
- deleted pods directory
- deleted derived data 
- run flutter clean
- rebuild the app

Thanks in advance

**Comment by ken-ng-esotec** [comment]
Yes, this works. Thank you for the update

**Comment by bulwinkel** [comment]
`pod update` did the trick, thanks @ken-ng-esotec !
