### ISSUE TITLE
Receive "ERROR | WebSocketBloc | Shutting down with exception: NetworkException" after upgrading from Amplify Flutter 1.6 to 2.3 

### ISSUE THREAD

**Issue by stephenjen** [aws-amplify/amplify-flutter#5184]
### Description

Started to get the following error after upgrading from Amplify Flutter 1.6 to 2.3:

`flutter: ERROR | WebSocketBloc | Shutting down with exception: NetworkException {
  "message": "Exception from WebSocketService.",
  "underlyingException": "type '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>?' in type cast"
}
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      WebSocketBloc._emit (package:amplify_api_dart/src/graphql/web_socket/blocs/web_socket_bloc.dart:134:24)
#2      WebSocketBloc._shutdownWithException (package:amplify_api_dart/src/graphql/web_socket/blocs/web_socket_bloc.dart:549:5)
#3      WebSocketBloc._init.<anonymous closure> (package:amplify_api_dart/src/graphql/web_socket/blocs/web_socket_bloc.dart:283:9)
#4      _rootRunBinary (dart:async/zone.dart:1423:47)
#5      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1225:7)
#7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:384:15)
#8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#9      _BufferingStreamSubscription._addError (dart:async/stream_<…>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      WebSocketBloc._emit (package:amplify_api_dart/src/graphql/web_socket/blocs/web_socket_bloc.dart:134:24)
#2      WebSocketBloc._shutdownWithException (package:amplify_api_dart/src/graphql/web_socket/blocs/web_socket_bloc.dart:549:5)
#3      WebSocketBloc._init.<anonymous closure> (package:amplify_api_dart/src/graphql/web_socket/blocs/web_socket_bloc.dart:283:9)
#4      _rootRunBinary (dart:async/zone.dart:1423:47)
#5      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1225:7)
#7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:384:15)
#8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#9      _BufferingStreamSubscription._addError (dart:async/stream_<…>`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Prior to this error, the following is run:

1. Authenticator - user logs in
2. await Amplify.DataStore.stop(), then wait 1 sec and await Amplify.DataStore.start();
3. Set a listener for sync progress `dbListener = Amplify.Hub.listen(HubChannel.DataStore, (dynamic hubEvent) async {}`

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.3

### Amplify Flutter Version

2.3.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @stephenjen, thanks for reporting.

Can you provide your GraphQL schema? 

Are you able to sync models at any point? For example, a fresh app start with a stored user session?

**Comment by stephenjen** [comment]
Here's my schema.graphql:

`type Tag @model @auth(rules: [{allow: private}]) {
    id: ID!
    name: String! @index(name: "byName")
    scheduledBlocks: [ScheduledBlock] @manyToMany(relationName: "ScheduledBlockTag")
    #  trayBlocks: [TrayBlock] @manyToMany(relationName: "TrayBlockTag")
    trayBlocks: [TrayBlock] @hasMany(indexName: "TrayBlockTag")
    seriess: [Series] @manyToMany(relationName: "SeriesTag")
    metrics: [Metric] @manyToMany(relationName: "MetricTag")
    userStatsPerformanceModeMetricsAdherence: [UserStatsPerformanceModeMetricsAdherence] @hasMany(indexName: "byTag", fields: ["id"])
}

#  ScheduledBlock
type ScheduledBlock @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
    id: ID!
    title: String!
    startTime: AWSDateTime!
    endTime: AWSDateTime!
    duration: Float
    tags: [Tag] @manyToMany(relationName: "ScheduledBlockTag")
    #    activities: [Activity] @hasMany(indexName: "byScheduledBlock", fields: ["id"])
    trayBlockID: ID @index(name: "byTrayBlock", sortKeyFields: ["title"])  # problem
    trayBlock: TrayBlock @belongsTo(fields: ["trayBlockID"])  # problem
    #  seriesTrayBlockID: ID @index(name: "bySeriesTrayBlock", sortKeyFields: ["title"])
    #  seriesTrayBlock: SeriesTrayBlock @belongsTo(fields: ["seriesTrayBlockID"])
    pOwner: String
}

type Metric @model @auth(rules: [{allow: private}]) {
    id: ID!
    title: String!
    duration: Int!
    priority: Int!
    operationModeID: ID! @index(name: "byOperationMode", sortKeyFields: ["title"])
    operationMode: OperationMode! @belongsTo(fields: ["operationModeID"])
    tags: [Tag] @manyToMany(relationName: "MetricTag")
}

#  UserOperationMode
type UserOperationMode @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
    id: ID!
    date: AWSDateTime!
    operationModeID: ID @index(name: "byOperationModeUserOperationMode", sortKeyFields: ["date"]) # problem
    operationMode: OperationMode @belongsTo(fields: ["operationModeID"]) # problem
    pOwner: String!
    test: String
}

type Settings @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    id: ID!
    name: String!
    value: String!
    pOwner: String!
}

# OperationMode
type OperationMode @model @auth(rules: [{allow: private}]) {
    id: ID!
    title: String!
    shortDescription: String
    description: String!
    longDescription: String
    featured: Boolean!
    featuredPriority: Int!
    category: String!
    categoryPriority: Int!
    metric: [Metric] @hasMany(indexName: "byOperationMode", fields: ["id"])
    userOperationMode: [UserOperationMode] @hasMany(indexName: "byOperationModeUserOperationMode", fields: ["id"])  # problem
    series: [Series] @hasMany(indexName: "bySeries", fields: ["id"])
    trayBlocks: [TrayBlock] @manyToMany(relationName: "OperationModeTrayBlock")  # problem
    profileImage: String
    featuredProfileImage: String
    authorID: ID @index(name: "byAuthor", sortKeyFields: ["title"])
    author: Author @belongsTo(fields: ["authorID"])
    shares: [Share] @manyToMany(relationName: "ShareOperationMode")
    #    shareID: ID @index(name: "byOperationModeShare", sortKeyFields: ["id"])
    #    share: Share @belongsTo(fields: ["shareID"])
    activities: [Activity] @hasMany(indexName: "byOperationMode", fields: ["id"])
    stats: [UserStatsOperationMode] @hasMany(indexName: "byOperationMode", fields: ["id"]) # problem
}

type Author @model @auth(rules: [{allow: private}]) {
    id: ID!
    fname: String!
    lname: String!
    mname: String
    description: String
    profileImage: String
    operationModes: [OperationMode] @hasMany(indexName: "byAuthor", fields: ["id"])
}

type Series @model @auth(rules: [{allow: private}]) {
    id: ID!
    title: String!
    description: String!
    longDescription: String!
    tags: [Tag] @manyToMany(relationName: "SeriesTag")
    operationModeID: ID! @index(name: "bySeries", sortKeyFields: ["title"])
    operationMode: OperationMode! @belongsTo(fields: ["operationModeID"])
    shares: [Share] @manyToMany(relationName: "ShareSeries")
    #    shareID: ID @index(name: "bySeriesShare", sortKeyFields: ["id"])
    #    share: Share @belongsTo(fields: ["shareID"])
    trayBlocks: [SeriesTrayBlock] @hasMany(indexName: "bySeriesSeriesTrayBlockA", fields: ["id"])
    activities: [Activity] @hasMany(indexName: "bySeriesActivity", fields: ["id"])
    recommendedStartTime: String
    recommendedStartTimeTime: AWSDateTime
    recommendedEndTimeTime: AWSDateTime
    featured: Boolean
    featuredPriority: Int
    duration: String
    recommendedTimeOfDay: String
    image: String
}

type TrayBlock @model @auth(rules: [{allow: private}]) {
    id: ID!
    title: String!
    description: String!
    longDescription: String
    oneWordDescription: String
    duration: Int!
    #  tags: [Tag] @manyToMany(relationName: "TrayBlockTag")
    tagID: ID! @index(name: "TrayBlockTag", sortKeyFields: ["id"])
    tag: Tag! @belongsTo(fields: ["tagID"])
    seriess: [SeriesTrayBlock] @hasMany(indexName: "byTrayBlockSeriesA", fields: ["id"])
    operationModes: [OperationMode] @manyToMany(relationName: "OperationModeTrayBlock")  # problem
    scheduledBlocks: [ScheduledBlock] @hasMany(indexName: "byTrayBlock", fields: ["id"])  # problem
}

type SeriesTrayBlock @model @auth(rules: [{allow: private}]) {
    id: ID!
    sequence: Int
    seriesID: ID! @index(name: "bySeriesSeriesTrayBlockA", sortKeyFields:["id"])
    trayBlockID: ID! @index(name: "byTrayBlockSeriesA", sortKeyFields:["id"])
    series: Series @belongsTo(fields: ["seriesID"])
    trayBlock: TrayBlock @belongsTo(fields: ["trayBlockID"])
    #  scheduledBlocks: [ScheduledBlock] @hasMany(indexName: "bySeriesTrayBlock", fields: ["id"])
}

#type Friend @model @auth(rules: [{ allow: owner, ownerField: "pOwner"  }{ allow: private, operations: [read] }]) {
type Friend @model @auth(rules: [{ allow: private, ownerField: "pOwner"  }]) {
    id: ID!
    profileID: ID @index(name: "byProfile", sortKeyFields: ["id"]) # had to remove the ! here for activity to work
    profile: Profile @belongsTo(fields: ["profileID"]) # had to remove the ! here for activity to work
    activities: [Activity] @hasMany(indexName: "byFriend", fields: ["id"])
    approved: Boolean
    blocked: Boolean
    pOwner: String!
}
enum ActivityAction {
    STARTEDSCHEDULING
    ADDEDFRIEND
    CHANGEDOPERATIONMODE
    COMPLETIONPROGRESS
    USEDSERIES
    ACHIEVEDGOALS
    ALMOSTACHEIVEDGOALS
    UPLOADEDIMAGE
    MODIFIEDSCHEDULE
    MODIFIEDSCHEDULEMAJOR
    LIKEDACTIVITY
    LIKEDSERIES
    LIKEDBLOCK
    LIKEDACHIEVEDGOALS
    LIKEDCOMMENT
    LIKEDUPLOAD
    COMMENTEDACTIVITY
    COMMENTEDSERIES
    COMMENTEDBLOCK
    COMMENTEDACHEIVEDGOALS
    COMMENTEDALMOSTACHEIVEDGOALS
}
#type Activity @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [create, delete, read, update] }]) {
type Activity @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    #  id: ID! @primaryKey(sortKeyFields: ["action", "pOwner", "date"])
    id: ID!
    date: AWSDateTime!
    action: ActivityAction!
    friendID: ID! @index(name: "byFriend", sortKeyFields: ["date"])
    friend: Friend! @belongsTo(fields: ["friendID"])
    friendsListID: ID @index(name: "byFriendsList", sortKeyFields: ["id"])
    friendsList: FriendsList @belongsTo(fields: ["friendsListID"])
    #    scheduledBlockID: ID @index(name: "byScheduledBlock", sortKeyFields: ["date"])
    #    scheduledBlock: ScheduledBlock @belongsTo(fields: ["scheduledBlockID"])
    operationModeID: ID @index(name: "byOperationMode", sortKeyFields: ["date"])
    operationMode: OperationMode @belongsTo(fields: ["operationModeID"])
    comments: [Comment] @hasMany(indexName: "byActivityC", fields: ["id"])
    seriesID: ID @index(name: "bySeriesActivity", sortKeyFields: ["date"])
    series: Series @belongsTo(fields: ["seriesID"])
    pOwnerProfileID: ID @index(name: "activitiesByProfile", sortKeyFields: ["date"])
    pOwnerProfile: Profile @belongsTo(fields: ["pOwnerProfileID"])
    completionPercentages: AWSJSON
    countedSchedules: [String!]
    pOwner: String!
}

#type Like @model @auth(rules: [{ allow: owner, ownerField: "pOwner"  }{ allow: private, operations: [create, delete, read, update] }]) {
type Like @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    id: ID!
    #    activityID: ID! @index(name: "byActivity", sortKeyFields: ["id"])
    #    activity: Activity! @belongsTo(fields: ["activityID"])
    shareID: ID! @index(name: "byShare", sortKeyFields: ["id"])
    share: Share! @belongsTo(fields: ["shareID"])
    content: String
    pOwner: String!
}

#type Comment @model @auth(rules: [{ allow: owner, ownerField: "pOwner"  }{ allow: private, operations: [create, delete, read, update] }]) {
type Comment @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    id: ID!
    activityID: ID! @index(name: "byActivityC", sortKeyFields: ["id"])
    activity: Activity! @belongsTo(fields: ["activityID"])
    content: String!
    pOwner: String!
}
type Profile @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    id: ID!
    userName: String
    fname: String
    lname: String
    profileImage: String
    remoteImageURL: String
    bio: String
    pOwner: String!
    friends: [Friend] @hasMany(indexName: "byProfile", fields: ["id"])
    activities: [Activity] @hasMany(indexName: "activitiesByProfile", fields: ["id"])
    shares: [Share] @hasMany(indexName: "sharesByProfile", fields: ["id"])
    onboarded: Boolean
}

type UserStatsPerformanceModeCategoriesUsed @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
    id: ID!
    pOwner: String!
    lastUpdated: AWSDateTime!
    year: Int!
    category: String!
    m1: Int
    m2: Int
    m3: Int
    m4: Int
    m5: Int
    m6: Int
    m7: Int
    m8: Int
    m9: Int
    m10: Int
    m11: Int
    m12: Int
}

type UserStatsDaysScheduled @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
    id: ID!
    pOwner: String!
    year: Int!
    lastUpdated: AWSDateTime!
    m1: Int
    m2: Int
    m3: Int
    m4: Int
    m5: Int
    m6: Int
    m7: Int
    m8: Int
    m9: Int
    m10: Int
    m11: Int
    m12: Int
    weeklyStats: String
}

type UserStatsOperationMode @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
    id: ID!
    pOwner: String!
    operationModeID: ID @index(name: "byOperationMode", sortKeyFields: ["lastUpdated"])
    operationMode: OperationMode @belongsTo(fields: ["operationModeID"])
    lastUpdated: AWSDateTime!
    year: Int
    m1: Int
    m2: Int
    m3: Int
    m4: Int
    m5: Int
    m6: Int
    m7: Int
    m8: Int
    m9: Int
    m10: Int
    m11: Int
    m12: Int
}

type UserStatsStreaks @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
    #type UserStatsStreaks @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    id: ID!
    pOwner: String!
    year: Int!
    lastScheduledDayOverall: AWSDateTime
    m1CountOverall: Int
    m2CountOverall: Int
    m3CountOverall: Int
    m4CountOverall: Int
    m5CountOverall: Int
    m6CountOverall: Int
    m7CountOverall: Int
    m8CountOverall: Int
    m9CountOverall: Int
    m10CountOverall: Int
    m11CountOverall: Int
    m12CountOverall: Int
    m1LongestStreakOverall: Int
    m2LongestStreakOverall: Int
    m3LongestStreakOverall: Int
    m4LongestStreakOverall: Int
    m5LongestStreakOverall: Int
    m6LongestStreakOverall: Int
    m7LongestStreakOverall: Int
    m8LongestStreakOverall: Int
    m9LongestStreakOverall: Int
    m10LongestStreakOverall: Int
    m11LongestStreakOverall: Int
    m12LongestStreakOverall: Int
}

type UserStatsPerformanceModeMetricsAdherence @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
    id: ID!
    pOwner: String!
    year: Int!
    tagID: ID! @index(name: "byTag", sortKeyFields: ["year"])
    tag: Tag! @belongsTo(fields: ["tagID"])
    m1MetricQuota: Int
    m1MetricScheduled: Int
    m2MetricQuota: Int
    m2MetricScheduled: Int
    m3MetricQuota: Int
    m3MetricScheduled: Int
    m4MetricQuota: Int
    m4MetricScheduled: Int
    m5MetricQuota: Int
    m5MetricScheduled: Int
    m6MetricQuota: Int
    m6MetricScheduled: Int
    m7MetricQuota: Int
    m7MetricScheduled: Int
    m8MetricQuota: Int
    m8MetricScheduled: Int
    m9MetricQuota: Int
    m9MetricScheduled: Int
    m10MetricQuota: Int
    m10MetricScheduled: Int
    m11MetricQuota: Int
    m11MetricScheduled: Int
    m12MetricQuota: Int
    m12MetricScheduled: Int
}

type Share @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    id: ID!
    sharedDate: AWSDateTime!
    completionDate: AWSDateTime!
    note: String
    #    seriess: [Series] @hasMany(indexName: "bySeriesShare", fields: ["id"])
    #    operationModes: [OperationMode] @hasMany(indexName: "byOperationModeShare", fields: ["id"])
    seriess: [Series] @manyToMany(relationName: "ShareSeries")
    operationModes: [OperationMode] @manyToMany(relationName: "ShareOperationMode")
    numberOfBlocks: Int
    completionPercentages: AWSJSON
    likes: [Like] @hasMany(indexName: "byShare", fields: ["id"])
    pOwnerProfileID: ID @index(name: "sharesByProfile", sortKeyFields: ["sharedDate"])
    pOwnerProfile: Profile @belongsTo(fields: ["pOwnerProfileID"])
    imageURL: String
    pOwner: String!
}

# this is post and activity is comments
type FriendsList @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
    id: ID!
    friendsIds: [String!]!
    activities: [Activity] @hasMany(indexName: "byFriendsList", fields: ["id"])
    pOwner: String!
}
`

I just noticed that in my model/ directory for some of these models I see the following:

`ShareSeries.fromJson(Map<String, dynamic> json)  `

Not sure if the `Map<String, dynamic>` is the `'_Map<String, dynamic>'` from the error message. 

After I hot restart, I still get the error and the sync starts.

**Comment by stephenjen** [comment]
I think I see were the error is occurring.  As I mentioned before, I have the following code:

```
await Amplify.DataStore.stop();
await Future.delayed(const Duration(seconds: 1));
await Amplify.DataStore.start();
```

Before I was able to call `await Amplify.DataStore.stop();` regardless if DataStore has already .start() or not, but now it throw the error in my original post.  Removing `await Amplify.DataStore.stop();` and just calling `await Amplify.DataStore.start();` seems to be the fix.  Incidentally, starting the DataStore if it has already been started also causes the error in my original post.  

Question - how can I determine if DataStore is already running?

**Comment by Jordan-Nelson** [comment]
@stephenjen - I don't believe there is a way to check if DataStore is running. Calling any data store method (start, query, observe, etc.) other than `.clear()` and `.stop()` will automatically start DataStore if it is not already running. `.clear()` and `.stop()` will stop it. So if you have called a DataStore method without calling clear/stop, it will be running.

**Comment by Jordan-Nelson** [comment]
Am I correct in understanding that to reproduce this issue you can do either of the following?
1. call DataStore.stop() when DataStore is not currently running
2. call DataStore.start() when DataStore is already running

**Comment by stephenjen** [comment]
@Jordan-Nelson that seems to be the case, but I'm investigating the reason why when user logout and log back in the error occurs no matter what.

**Comment by Jordan-Nelson** [comment]
@stephenjen Thanks. We will attempt to reproduce this. I will let you know if we need any more info.

**Comment by harrynguyen2510** [comment]
any update?

**Comment by stephenjen** [comment]
@Jordan-Nelson I've removed all `DataStore.stop()` and `DataStore.start()`, and only have a `DataStore.query()` query statement to start up DataStore and a `DataStore.clear()` after user logs out.

On a fresh install of the app, after user logs in DataStore starts up and completes sync without errors, but after logging out and logging back in, the same code is run, I get the errors in OP.

**Comment by harrynguyen2510** [comment]
@stephenjen  In my case I call .stop and .start when App.resumed. Because I want to trigger 'ready' Datastore event from Amplify.Hub.listen(HubChannel.DataStore...), then I got this error
How do you handle when app resumes with Datastore, making sure all data is ready?

**Comment by Jordan-Nelson** [comment]
So far I have been unable to reproduce this, but I am still working on it.

@harrynguyen2510 do you see the same exception as in the original issue description?

**Comment by Jordan-Nelson** [comment]
@stephenjen - I did not realize that you had also opened https://github.com/aws-amplify/amplify-flutter/issues/5143, which looks similar. I see you were previously using version 1.6 and were seeing an issue where data was not syncing. Then after upgrading to version 2.3, in addition to data not syncing, you see this error message. Is that accurate?

Starting with version 2.2, API requests from within DataStore (on iOS) are made from dart. Prior to this version they were made from native iOS code. The logs from native iOS code do not show unless you are debugging from Xcode, whereas the logs from dart code will be visible in a regular flutter debug session (from VS Code, Android Studio, or the terminal).

It sounds like the issue you are facing on version 1.6 and 2.3 may be the same. However, you are seeing additional logs when using version 2.3 since the calls are made from Dart. Would you agree with this? If so, I may close out https://github.com/aws-amplify/amplify-flutter/issues/5143 in favor of this issue so that we can track the issue in once location.

**Comment by stephenjen** [comment]
Hi @Jordan-Nelson,

Thanks for sharing additional details of the changes from 1.6 to 2.2.  So far, I can lean towards stating these two issues seem unrelated but possibly can both be fixed by the upgrade.  I have not been able to test the original issue [5143](https://github.com/aws-amplify/amplify-flutter/issues/5143) that prompted me to upgrade, as after the upgrade I started to  encounter the issue reported in this ticket.

**Comment by stephenjen** [comment]
@Jordan-Nelson, got some interesting updates to share.

After spending time progressively commenting out more and more fields and models to try to get to a better understanding of what may be causing this error, I realized the error doesn't seem to be related to any particular fields or models, but to the total number of models in my schema.graphql.

I created 17 identical models:

  ```
  type Tag @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
      id: ID!
      title: String!
      pOwner: String!
  }
  
  type Tag1 @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
      id: ID!
      title: String!
      pOwner: String!
  }
  
  type Tag2 @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
      id: ID!
      title: String!
      pOwner: String!
  }
  ...
  ...
  ...
  type Tag16 @model @auth(rules: [{ allow: owner }]) {
      id: ID!
      title: String!
      pOwner: String!
  }
  ```
With 17 models I get the error, but removing the 17th model then I don't get the error.  
  
Here's the code I used to test this:  

  ```
import 'dart:async';
import 'dart:ui';

import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_authenticator/amplify_authenticator.dart';
import 'package:amplify_storage_s3/amplify_storage_s3.dart';
import 'package:flutter/material.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:rectangles/amplifyconfiguration.dart';
import 'models/ModelProvider.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Authenticator(
      child: MaterialApp(
        title: 'Test',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  late StreamSubscription<DataStoreHubEvent> dbListener;
  late var subscription;

  bool networkIsUp = false;

  Future<void> observeEvents() async {
    print('inside observeEvents');

    dbListener = Amplify.Hub.listen(HubChannel.DataStore, (dynamic hubEvent) async {
      String msg = '';

      switch (hubEvent.eventName) {
        case 'networkStatus':
          NetworkStatusEvent nse = hubEvent.payload as NetworkStatusEvent;
          msg = 'Amplify hub event - network status is ${nse?.active.toString()}';

          break;
        case 'subscriptionsEstablished':
          msg = 'Amplify hub event - starting to sync from cloud...';
          break;
        case 'syncQueriesStarted':
          msg = 'Amplify hub event - syncing...';
          break;
        case 'modelSynced':
          ModelSyncedEvent mse = hubEvent.payload as ModelSyncedEvent;

          msg = 'Amplify hub event - ${mse.modelName} has been sync\'d from cloud, ${mse.added}, ${mse.updated} ...';
          break;
        case 'syncQueriesReady':
          msg = 'Amplify hub event - sync is done';
          break;
        case 'ready':
          msg = 'Amplify hub event - datastore is ready';

          break;
        case 'outboxMutationEnqueued':
          msg = 'Amplify hub event - local change has been newly staged';
          break;
        case 'outboxMutationProcessed':
          OutboxMutationEvent ome = hubEvent.payload as OutboxMutationEvent;

          msg = 'Amplify hub event - outboxMutationProcessed local change has finished synchronization with the Cloud';
          break;
        case 'outboxStatus':
          OutboxStatusEvent ose = hubEvent.payload as OutboxStatusEvent;
          msg = 'Amplify hub event - outboxStatus local change has finished synchronization with the Cloud';
          break;
        default:
          break;
      }
      if (msg != '') print(msg);
    });
    subscription = Amplify.Hub.listen(HubChannel.Auth, (AuthHubEvent event) {
      print('inside subscription');
      switch (event.type) {
        case AuthHubEventType.signedIn:
          safePrint('User is signed in.');
          Amplify.DataStore.query(Tag.classType).then((s) {
            print('s.length ${s.length}');
          });
          break;
        case AuthHubEventType.signedOut:
          safePrint('User is signed out.');
          break;
        case AuthHubEventType.sessionExpired:
          safePrint('The session has expired.');
          break;
        case AuthHubEventType.userDeleted:
          safePrint('The user has been deleted.');
          break;
      }
    });
  }

  Future<void> _initializeApp() async {
    await _configureAmplify();
  }

  Future<void> _configureAmplify() async {
    if (!Amplify.isConfigured) {
      print('_configureAmplify() configuring amplify');
      try {
        AmplifyDataStore datastorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);
        final storage = AmplifyStorageS3();
        final api = AmplifyAPI();
        final auth = AmplifyAuthCognito();

        await Amplify.addPlugins([
          auth,
          datastorePlugin,
          storage,
          api,
        ]);
        await Amplify.configure(amplifyconfig);
      } catch (e) {
        print('An error occurred while configuring Amplify: $e');
      }
    }

    await observeEvents();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  void didChangeDependencies() {
    print('didChangeDependencies - setting subscription');
    _initializeApp();
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: Authenticator.builder(),
      home: Scaffold(
        body: Center(
          child: TextButton(
            onPressed: () {
              Amplify.DataStore.clear().then((s) {
                print('datastore cleared');
                Amplify.DataStore.stop().then((e) {
                  print('datastore stopped');
                  Amplify.Auth.signOut();
                });
              });
            },
            child: Text('Loggout'),
          ),
        ),
      ),
    );
  }
}
  ```

**Comment by Jordan-Nelson** [comment]
@stephenjen - Thanks for the info. We will try to reproduce with the new info.

**Comment by stephenjen** [comment]
Opps, I just saw this for Flutter Amplify V2:

<img width="697" alt="image" src="https://github.com/user-attachments/assets/bc1fb0c6-5d53-44d2-b4fe-c7fe98b48335">

I must be using 6 subscriptions somehow , so 6 x 17 = 102 which is over the 100 subscriptions per connection limit.  Will look into how these are calculated and how they can be increased.

**Comment by harrynguyen2510** [comment]
@Jordan-Nelson yes
@stephenjen I only used 13 model (39 subscriptions) in total but still got WebSocketBloc issue

**Comment by Jordan-Nelson** [comment]
Thanks for the additional info. We can look into the number of subscriptions. Even though you should be will below the 100 limit, if subscriptions are not getting cleaned up (for example, after stop/start) than it is possible that the 100 limit is being exceeded.

**Comment by stephenjen** [comment]
@Jordan-Nelson That's a great point.  I'm only getting this error the second time sync is initiated - no error for sync after app install and first log in, but error for sync after log out and log back in.

**Comment by stephenjen** [comment]
@Jordan-Nelson I changed the number of models to 10, and after the 3rd login-sync-logout cycle, on the 4th cycle I get the errors.

**Comment by stephenjen** [comment]
I downgraded Amplify Flutter from 2.3.0 to 2.2.0, 2.1.0 and finally to 2.0.0.  The error goes away at 2.0.0:

amplify_flutter: 2.0.0
amplify_datastore: ^2.0.0
amplify_auth_cognito: ^2.0.0
amplify_authenticator: ^2.0.0
amplify_api: ^2.0.0
amplify_storage_s3: ^2.0.0

@harrynguyen2510 give this a try, see if it works for you.

**Comment by Equartey** [comment]
Hi @stephenjen, thank you for your patience. 

We have been able to reproduce this issue and produce a solution. We will notify you when its available.

**Comment by NikaHsn** [comment]
I'm going to close this issue as the fix has been released in [2.4.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v2.4.0) version. If you see otherwise or have additional questions, please open a new issue.

**Comment by jamontesg** [comment]
I continuos with the same error.  


flutter: ERROR | WebSocketBloc - fb75ea94-3f65-45d9-b762-0e4fed1ae8aa | Shutting down with exception: NetworkException {
  "message": "Exception from WebSocketService.",
  "underlyingException": "type '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>?' in type cast"
}
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close



  amplify_analytics_pinpoint: 2.4.0
  amplify_api: 2.4.0
  amplify_api_dart: 0.5.4
  amplify_auth_cognito: 2.4.0
  amplify_authenticator: 2.1.2

  amplify_core: 2.4.0
  amplify_datastore: 2.4.0
  amplify_datastore_plugin_interface: 2.4.0
  amplify_flutter: 2.4.0
  amplify_storage_s3: 2.4.0
  


I made a flutter clean and error persist.

**Comment by stephenjen** [comment]
@jamontesg I had to downgrade to 2.0.0 in order for this error to go away.  Otherwise I think you'd need to wait for this fix to be merged into next update.

**Comment by harrynguyen2510** [comment]
Hey, 2.0.0 works for me
I talked to support from amplify
Main reason is over 2.0.0 works well if you're app is Gen 2. If you're app still gen q1. It's still getting bug even latest version released 
Because gen2 doesn't use datastore, they will show how you merge gen 1 to 2 in advance

**Comment by Equartey** [comment]
@jamontesg sorry to hear you're still having issues. How many models do you have?

@stephenjen @harrynguyen2510 This issue should be resolved in 2.4.0. Can yall verify the error is resolved?

**Comment by jamontesg** [comment]
hi @Equartey I have 18 models
issue is present only on IOS, android works without problems
(tests on emulators)

**Comment by Equartey** [comment]
Hi @jamontesg, I improved the error handling of the web socket so we can see the underlying error message. I'm curious to see what the error message after this change. Can you try your workflow again on the latest amplify version, but add this override? 

```dart
dependency_overrides:
  amplify_api_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: 995e6bdf2c0897dc2f0545c3c3bd347dc2619d80
      path: packages/api/amplify_api_dart
```

**Comment by jamontesg** [comment]
hi @Equartey   this is the error:

flutter: User is signed in.
[log] -->0
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 100 subscriptions reached"
    }
  ]
}

**Comment by Equartey** [comment]
@jamontesg Thank you.

I suspected that was the error. This would be a separate issue from the original one posted here.

 I'm going to need more info in order to understand why its not working on iOS, but is on Android. Can you please open a [new issue](https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&projects=&template=BUG-REPORT.yaml) regarding this? Be sure to include your schema and repro steps.

**Comment by jamontesg** [comment]
Thanks @Equartey   issue [#5383](https://github.com/aws-amplify/amplify-flutter/issues/5383)

**Comment by stephenjen** [comment]
@Equartey 

I'm on 2.4.1 and get this error after log on and log off (which starts and stop datastore for my app) the 3rd time
`
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "UnknownOperationError",
      "message": "Unknown operation id c5d52a2f-f184-4cbe-8599-2554e2ff2eca"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "UnknownOperationError",
      "message": "Unknown operation id fdcb1842-63cb-4da3-ad81-77bf82262186"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "UnknownOperationError",
      "message": "Unknown operation id de2f07d8-730b-4a5b-b2f7-ba0a794847fc"
    }
  ]
}
...
...
...
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 200 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 200 subscriptions reached"
    }
  ]
}
flutter: ERROR | WsSubscriptionBloc | {
  "errors": [
    {
      "errorType": "MaxSubscriptionsReachedError",
      "message": "Max number of 200 subscriptions reached"
    }
  ]
}
`

**Comment by Equartey** [comment]
@stephenjen hmm, looks like the subscriptions aren't getting cleared when restarting DataStore. 

Can you provide the code snippet for your sign-in/sign-out logic where you start/stop DataStore?

**Comment by stephenjen** [comment]
@Equartey 

Sign in:
```
  await Amplify.DataStore.stop();
  await Future.delayed(const Duration(seconds: 1));
  await Amplify.DataStore.start();
```

Sign out:
```
                            await Amplify.DataStore.stop().then((s) async {
                              print('DataStore stopped');
                              await Amplify.DataStore.clear().then((s) {
                                print('DataStore cleared');
                                signOff();
                              });
                            });
```

**Comment by stephenjen** [comment]
@Equartey , I went back to the test script I posted above and got no error in 2.4.1!  So I replaced all DataStore.start() in my code to DataStore.query(), that solved it 👍🏼👍🏼👍🏼

Thanks everyone on this thread for all your help 🙌🏼
